import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/Header";
import { WEBSITE } from "../utils/const";

export const metadata: Metadata = {
  title: "Neowiki",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className="font-sans min-h-screen flex flex-col">
        <Header 
          siteName="neoworks" 
          navigationItems={[
            { href: "/", label: "home" },
            { href: "/w/네오위키:개인정보처리방침", label: "privacy" }
          ]} 
        />
        <main className="flex-1 flex flex-col">
          {children}
        </main>
      </body>
    </html>
  );
} 